baseURL: "https://haidarzaki.github.io/Portfolio-Dzakiyuddin/"
languageCode: "en-us"
title: "Muhammad Dzakiyuddin Haidar"
theme: hugo-profile

outputs:
  home: ["HTML", "RSS", "JSON"]
  page: ["HTML", "RSS"]

enableRobotsTXT: true

pagination:
  pagerSize: 3

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  staticPath: "/Portfolio-Dzakiyuddin" # penting untuk Project Pages agar asset path benar
  useBootstrapCDN: true
  title: "Muhammad Dzakiyuddin Haidar"
  description: "Data Analyst Portfolio"
  favicon: "/Portfolio-Dzakiyuddin/fav.png" # path diperbaiki

  # --- NAVBAR ---
  navbar:
    align: ms-auto
    brandName: "Muhammad Dzakiyuddin Haidar"
    disableSearch: true
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # --- HERO ---
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Muhammad Dzakiyuddin Haidar"
    subtitle: "Data Analyst | Turning Data into Insights"
    content: "Fresh graduate in Informatics specializing in data analysis, visualization, and storytelling. Skilled in Python, SQL, and dashboards (Power BI, Tableau)."
    image: "/Portfolio-Dzakiyuddin/images/profile.jpeg" # path diperbaiki
    bottomImage:
      enable: true
    button:
      enable: true
      name: "Resume"
      url: "/Portfolio-Dzakiyuddin/images/cv.pdf" # path diperbaiki
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/haidarzaki
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/muhammad-dzakiyuddin-haidar/
        - icon: fab fa-instagram
          url: https://www.instagram.com/haidarzakii/

  # --- ABOUT ---
  about:
    enable: true
    title: "About Me"
    image: "/Portfolio-Dzakiyuddin/images/profile.jpeg" # path diperbaiki
    content: |
      I’m a fresh graduate who enjoys turning data into clear, actionable insights. Interests: data visualization, dashboard development, and understanding digital behavior.
    skills:
      enable: true
      title: "Tools & Technologies"
      items:
        - Python
        - SQL
        - Power BI / Tableau / Looker Studio
        - Streamlit
        - Figma
        - HTML/CSS/JS

  # --- PROJECTS ---
  projects:
    enable: true
    items:
      - title: "Telpass — Digital Leave Management"
        content: "Streamlined leave requests with responsive UI and research-driven UX."
        image: "/Portfolio-Dzakiyuddin/images/projects/telpass.png" # path diperbaiki
        badges: ["HTML", "CSS", "JavaScript", "Tailwind"]
        links:
          - icon: fab fa-github
            url: https://github.com/haidarzaki/Telpass
      - title: "SME Digital Readiness Analysis — BRIN"
        content: "EDA for 120+ SMEs with maturity categorization and dashboards."
        image: "/Portfolio-Dzakiyuddin/images/projects/brin.png" # path diperbaiki
        badges: ["Python", "Visualization"]
        links:
          - icon: fa fa-link
            url: "https://doi.org/10.1109/ASIANComNet63184.2024.10811067"
